//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JerarquiaEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDepartamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblDepartamento()
        {
            this.tblSubDepartamento = new HashSet<tblSubDepartamento>();
        }
    
        public int IdDepartamento { get; set; }
        public string NomDepartamento { get; set; }
        public string NomGerenteDpto { get; set; }
        public Nullable<int> TelGerenteDpto { get; set; }
        public Nullable<System.DateTime> FechaNacimtGerenteDpto { get; set; }
        public Nullable<System.DateTime> FechaInicioGerenciaDpto { get; set; }
        public int NitEmpresa { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubDepartamento> tblSubDepartamento { get; set; }
    }
}
