//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JerarquiaEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmpresa()
        {
            this.TblDepartamento = new HashSet<TblDepartamento>();
        }
    
        public int NitEmpresa { get; set; }
        public string NomEmpresa { get; set; }
        public Nullable<int> TelEmpresa { get; set; }
        public string DirEmpresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDepartamento> TblDepartamento { get; set; }
    }
}
