//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JerarquiaEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubDepartamento
    {
        public int IdSubDepartamento { get; set; }
        public string NomSubDepartamento { get; set; }
        public string NomGerenteSubDpto { get; set; }
        public Nullable<int> TelGerenteSubDpto { get; set; }
        public Nullable<System.DateTime> FechaNacimtGerenteSubDpto { get; set; }
        public Nullable<System.DateTime> FechaInicioGerenciaSubDpto { get; set; }
        public int IdDepartamento { get; set; }
    
        public virtual TblDepartamento TblDepartamento { get; set; }
    }
}
