<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="JerarquiaEmpresa._Default" EnableEventValidation="false" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

  

    <table class="nav-justified">
            <tr>
                
                <td class="auto-style2" style="text-align:left;background-color:aqua ">
                    <h3 style="width: 331px">LISTA DE EMPRESAS</h3>
                    <asp:GridView ID="tblListaEmpresa" runat="server" CellPadding="4" CssClass="auto-style1" ForeColor="#333333" GridLines="None"  OnRowDeleting="tblListaEmpresa_RowDeleting" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="tblListaEmpresa_SelectedIndexChanged4">
                        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                        <EditRowStyle BackColor="#999999" />
                        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#E9E7E2" />
                        <SortedAscendingHeaderStyle BackColor="#506C8C" />
                        <SortedDescendingCellStyle BackColor="#FFFDF8" />
                        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                    </asp:GridView>
                    <button type="button"  data-toggle="modal" data-target="#ModalEmpresa" class="Agg">Agregar Empresa</button>
                    <%--<asp:Button runat="server" ID="btnAgregarEmpresa" Text="Agregar empresa" />--%>
                </td>               
                <td class="auto-style2" style="text-align:center;background-color:aqua ">
                <h3 style="width: 287px">LISTA DEPARTAMENTOS</h3>
                        <asp:GridView ID="tblListaDepartamento" runat="server" CellPadding="4" CssClass="auto-style1" ForeColor="#333333" GridLines="None" Height="47px" Width="16px" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="tblListaDepartamento_SelectedIndexChanged">
                            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                            <EditRowStyle BackColor="#999999" />
                            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#E9E7E2" />
                            <SortedAscendingHeaderStyle BackColor="#506C8C" />
                            <SortedDescendingCellStyle BackColor="#FFFDF8" />
                            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                        </asp:GridView>
                    <button type="button"  data-toggle="modal" data-target="#ModalDepartamento" class="Agg" >Agregar Departamento</button>
                    <%--<asp:Button runat="server" ID="btnAgregarDepartamento" Text="Agregar Departamento" Style="text-align:left"/--%>
                </td>
                <td class="auto-style2" style="text-align:right; background-color:aqua; " >
                    <h3 style="width: 341px">LISTA SUBDEPARTAMENTOS</h3>
                    <asp:GridView ID="btlListaSubDepartamento" runat="server" CellPadding="4" CssClass="auto-style1" ForeColor="#333333" GridLines="None" OnSelectedIndexChanged="btlSubDepartamento_SelectedIndexChanged" AutoGenerateDeleteButton="True">
                        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                        <EditRowStyle BackColor="#999999" />
                        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#E9E7E2" />
                        <SortedAscendingHeaderStyle BackColor="#506C8C" />
                        <SortedDescendingCellStyle BackColor="#FFFDF8" />
                        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                    </asp:GridView>
                    <button type="button"  data-toggle="modal" data-target="#ModalSubDepartamento" class="Agg">Agregar</button>
                    <br />
                </td>               
              </tr>
           
        </table>

    
                
        
    <%--<a href="#mod" onclick="DetalleInsu(@item.idInsumo)"></a>--%>
    <%--<img src="~/Imagenes/add.png" type="button" data-toggle="modal" data-target="#ModalCateg" class="Agg" />--%>
    
    <%--Boton del modal registrar empresa--%>
    <%--<button type="button"  data-toggle="modal" data-target="#ModalEmpresa" class="Agg">Agregar</button>--%>

<!-- Modal -->
<div id="ModalEmpresa" class="modal fade" role="dialog" style="margin-top: 7%;">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div id="tituloCrearEmpresa" class="modal-header" style="padding:5px 50px">
                <button type="button" class="close" data-dismiss="modal" style="margin-top:2%;">&times;</button>
                <h4>REGISTRAR Empresa</h4>
            </div>
            <br />
            <header class="agileits-box-header clearfix">
               <%-- <form method="post" name="RegistrarEmpresa">--%>
                    <div class="form" style="margin-left:3.5%;">

                        <div style="width:48%; float:left; margin-left:13%">

                            <div class="form-group">
                                <label>Nombre de la empresa*</label>
                                <div class="campos">
                                    <asp:TextBox ID="txtnombreEmpresa" runat="server"></asp:TextBox>
                                </div>
                                <br>
                            </div>

                             <div class="form-group">
                                <label>Nit de la empresa*</label>
                                <div class="campos">
                                    <asp:TextBox ID="TxtNitEmpresa" runat="server"></asp:TextBox>
                                  <%--  @Html.EditorFor(model => model.Categoria.descripcion, new { htmlAttributes = new { @class = "form-control", @id = "descrCateg", @name = "descrCateg" } })
                                    @Html.ValidationMessageFor(model => model.Categoria.descripcion, "", new { @class = "text-danger" })--%>
    
                                </div>
                                <br>
                            </div>

                            <div class="form-group">
                                <label>Telefono de la empresa*</label>
                                <div class="campos">
                                    <asp:TextBox ID="TxtTelEmpresa" runat="server"></asp:TextBox>
                                </div>
                                <br>
                            </div>

                            <div class="form-group">
                                <label>Direccion de la empresa*</label>
                                <div class="campos">
                                    <asp:TextBox ID="TxtDireccion" runat="server"></asp:TextBox>
                                </div>
                                <br>
                            </div>

                            <div class="form-group" >
                            
                                <%--<input type="button" value="Guardar" class="btn" id="btnCateg" onClick="RegistrarEmpresa"/>--%>
                                <asp:Button ID="btnRegistrarEmpresa" runat="server" OnClick="Onclick_RegistrarEmpresa" Text="Registrarse"/>
                            </div>

                        </div>

                        
                    </div>
                <%--</form>--%>
            </header>
        </div>
    </div>
</div>
    <br />
    <hr />
    
    <br />
   
<!-- Modal -->

<div id="ModalDepartamento" class="modal fade" role="dialog" style="margin-top: 7%;">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div id="CrearDepartamento" class="modal-header" style="padding:5px 50px">
                <button type="button" class="close" data-dismiss="modal" style="margin-top:2%;">&times;</button>
                <h4>REGISTRAR DEPARTAMENTO</h4>
            </div>
            <br />
            <header class="agileits-box-header clearfix">
                <%--<form method="post" name="RegistrarDepartamento">--%>
                    <div class="form" style="margin-left:3.5%;">

                        <div style="width:48%; float:left; margin-left:13%">
    
                            <div class="form-group">
                                <label>Nombre del departamento*</label>
                                <div class="campos">
                                    <asp:TextBox ID="TxtDepartamento" runat="server"></asp:TextBox>
                                  <%--  @Html.EditorFor(model => model.Categoria.descripcion, new { htmlAttributes = new { @class = "form-control", @id = "descrCateg", @name = "descrCateg" } })
                                    @Html.ValidationMessageFor(model => model.Categoria.descripcion, "", new { @class = "text-danger" })--%>
                              </div>
                                <br>
                            </div>

                             <div class="form-group">
                                <label>Nombre gerente del departamento*</label>
                                <div class="campos">
                                    <asp:TextBox ID="TxtNomGerenDepart" runat="server"></asp:TextBox>                                 
                                </div>
                                <br>
                            </div>

                            <div class="form-group">
                                <label>Telefono gerente del departamento*</label>
                                <div class="campos">
                                    <asp:TextBox ID="TxtTelGerenteDepartamento" runat="server"></asp:TextBox>
                                </div>
                                <br>
                            </div>

                            <div class="form-group">
                                <label>Fecha nacimiento del gerente del departamento*</label>
                                <div class="campos">
                                    <asp:TextBox ID="TxtFechaNaciGerenteDpto" runat="server"></asp:TextBox>
                                </div>
                                <br>
                            </div>

                            <div class="form-group">
                                <label>Fecha inicio gerencia del departamento*</label>
                                <div class="campos">
                                    <asp:TextBox ID="TxtFechaIniGerenciaDpto" runat="server"></asp:TextBox>
                                </div>
                                <br>
                            </div>

                            <%--Falta combobox que muestre las empresas--%>

                             <%--<asp:DropDownList id="ComboboxListaEmpresas"
                                 runat="server"/>--%>

                            <%--OnSelectedIndexChanged="ComboboxListaEmpresaSelection_Change"--%>

                            <div class="form-group" >
                                <%--<asp:Button ID="BtnRegistrarDpto" runat="server" OnClick="Onclick_RegistrarDepartamento2" Text="Registrarse Dpto"/>--%>
                                <asp:Button ID="Button1" runat="server" Text="Registrarse Dpto" OnClick="Onclick_RegistrarDepartamento2" />
                                
                            </div>

                        </div>

                        
                    </div>
                <%--</form>--%>
            </header>
        </div>
    </div>
</div>


    <br />
    <hr />
    <br />

    
    <h1>&nbsp;</h1>
    <h1>&nbsp;</h1>
    <h1>&nbsp;</h1>
    <h1>&nbsp;</h1>
    <h1>&nbsp;</h1>
    <h1>&nbsp;</h1>
    <h1>&nbsp;</h1>
    
    

    <%--Boton del modal registrar Subdepartamentos--%>
    
    
<!-- Modal -->
<div id="ModalSubDepartamento" class="modal fade" role="dialog" style="margin-top: 7%;">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div id="CrearSubDepartamento" class="modal-header" style="padding:5px 50px">
                <button type="button" class="close" data-dismiss="modal" style="margin-top:2%;">&times;</button>
                <h4>REGISTRAR SUBDEPARTAMENTO</h4>
            </div>
            <br />
            <header class="agileits-box-header clearfix">
                <%--<form method="post" name="RegistrarSubDepartamento">--%>
                    <div class="form" style="margin-left:3.5%;">

                        <div style="width:48%; float:left; margin-left:13%">
                            <%--@Html.ValidationSummary(true, "", new { @class = "text-danger" })--%>

                            <div class="form-group">
                                <label>Nombre del SubDepartamento*</label>
                                <div class="campos">
                                    <asp:TextBox ID="txtNomSubDepartamento" runat="server"></asp:TextBox>
                                  <%--  @Html.EditorFor(model => model.Categoria.descripcion, new { htmlAttributes = new { @class = "form-control", @id = "descrCateg", @name = "descrCateg" } })
                                    @Html.ValidationMessageFor(model => model.Categoria.descripcion, "", new { @class = "text-danger" })--%>
                                </div>
                                <br>
                            </div>

                             <div class="form-group">
                                <label>Nombre gerente del SubDepartamento*</label>
                                <div class="campos">
                                    <asp:TextBox ID="txtNomGerentSubDepartamento" runat="server"></asp:TextBox>                                 
                                </div>
                                <br>
                            </div>

                            <div class="form-group">
                                <label>Telefono gerente del SubDepartamento*</label>
                                <div class="campos">
                                    <asp:TextBox ID="txtTelGerentSubDepartamento" runat="server"></asp:TextBox>
                                </div>
                                <br>
                            </div>

                            <div class="form-group">
                                <label>Fecha de nacimiento del gerente del SubDepartamento*</label>
                                <div class="campos">
                                    <asp:TextBox ID="txtFechaNaciGerentSubDpto" runat="server"></asp:TextBox>
                                </div>
                                <br>
                            </div>

                            <div class="form-group">
                                <label>Fecha de inicio de la gerencia del SubDepartamento*</label>
                                <div class="campos">
                                    <asp:TextBox ID="txtFechaIniGerenSubDpto" runat="server"></asp:TextBox>
                                </div>
                                <br>
                            </div>


                            <div class="form-group" id="btns">
                                
                                <asp:Button ID="btnRegistrarSubDepartamento" runat="server"  Text="Registrarse" OnClick="Onclick_RegistrarSubDepartamento" />                            
                            </div>

                        </div>

                        
                    </div>
                <%--</form>--%>
            </header>
        </div>
    </div>
</div>
</asp:Content>
